### ISSUE TITLE
Design account management experience

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#105]
### Context
We need to create designs for the ability to manage a Rally account.

### Relevant resources
* ➡️ **[FigJam -- User Flow & Backend Operations](https://www.figma.com/file/pQSJaS7xVGSMzyZeSpIBgR/User-Flow-%26-Backend-Operations?node-id=0%3A1)**
* [Design audit](https://miro.com/app/board/o9J_l4lk8f4=/)

### Requirements
- Re-imagine the UI placement of managing account (for example: upper right corner)
- Users should be able to have easy to understand access to everything they need to manage their account: 
  - Manage profile (edit questions)
  - update email (update Google SSO), cc: @rhelmer we need help from you here I believe
  - update password
  - log out of Rally
  - delete Rally completely (add friction)
 - All potential drop off points have been addressed via the design and/or documented notes (see salmon colored diamond sticky notes in user flow diagram, and brainstorm any others that we're missing)

### These need to be scoped per Product's requirements and new tickets need to be created. We also need to know if each of these should be part of MVP or not. @knowtheory @javaun to discuss & create new tickets. 🙏
- 2FA
- Account recovery 
- which devices are you used to log in (or are currently logged into)
  - 💬 [Slack thread with Rob](https://mozilla.slack.com/archives/C025YNEDGCB/p1629935316111400)
- more tightly aligned experience between the marketing site and the authenticated web platform
- additional content in the authenticated experience for studies

### Activities 
- [ ] Align on account management goals (everything a user must be able to do, and surfacing technical constraints) with team 
- [ ] Prototype user flow
- [ ] Collaborate with Engineering re: working with Firebase capabilities / options
- [ ] Plan for team discussion that solicits critique / reactions / responses about open questions and implementation details 
- [ ] Iterate based on feedback

### Acceptance criteria
Figma sketches / prototypes / design and discussion should create clarity and alignment for the team, and allow the engineering team to build.

### Deliverable
TBD: Figma design files

### Estimated size
1 cycle

**Comment by jepstein** [comment]
UX / Engineering sync planned for 11/4/2021 to produce something actionable for FE eng

**Comment by jepstein** [comment]
Scope and components identified in cross-functional -- https://docs.google.com/document/d/1vTWcEK-uLvaX4yifa-u17Oz3WI1S7uFSTnYCMDywspg/edit#
