### ISSUE TITLE
implement cloud functions for enrollment and deletion requests

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-web-platform#108]
Per the [proposal](https://docs.google.com/document/d/1AQpBaj8ll-MCYFyon10zsK7DgZ_n9tpTZZbaF-7ZInw/edit#), we need to handle enrollment pings and deletion requests.

The per-user firestore document structure looks like this:

```
users/{uid}
users/{uid}/studies/{studyId}
extensionUsers/{uid}
```

I think we can do platform enrollment with a few changes to the auth trigger functions that will land in https://github.com/mozilla-rally/rally-web-platform/pull/101.

- `onCreate`
  - `sendPlatformEnrollmentPing`
- `onDelete`: 
  - `sendPlatformDeletionPing`
  - `deleteRallyUser`
    - This deletes the above documents from Firestore

To handle individual study deletion and enrollment pings, we can use a [Firestore onDelete/onUpdate](https://firebase.google.com/docs/functions/firestore-events) trigger on the `extensionUsers/{uid}/studies/{studyId}` document, which contains the `enabled` state.

**Comment by rhelmer** [comment]
We need to make sure to send the demographics ping in too. I think it would make sense to have a trigger on the user document, this could handle both enrollment and demographics pings.

**Comment by rhelmer** [comment]
I have a branch where I've done a quick port of the rally core Glean setup to standalone cloud functions, seeking clarity right now on if `glean.js` supports node (we could probably make web content work too).

**Comment by aaga** [comment]
`glean.js` now has official node support. I am picking up @rhelmer 's prototype branch and refactoring.

Relevant docs: [proposal] https://docs.google.com/document/d/1IWQ8Jbv41l6FquRpkuIeE9NWFFaZ5JgBWZzy93naYQU/edit#heading=h.jy0mh3yfc64v

[eventual consistency] https://docs.google.com/document/d/1_YMA-EDoMMRHc65vVzAZExs0m4lj4CEzDGb1LfNAm04/edit#
