### ISSUE TITLE
consider using Google sign in with redirect vs. pop-up

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-web-platform#109]
I've been noticing that even though the Firebase docs mention that redirect is better for mobile and sign-up is more typical for desktop, that major Google properties seem to use the redirect sign-in method.

We should consider switching to it, should be pretty simple.

**Comment by hamilton** [comment]
This has been discussed a few times with UX, and I believe @mkhandekar decided to stick with the pop-up. It can of course be reconsidered but just wanted to flag

**Comment by rhelmer** [comment]
> This has been discussed a few times with UX, and I believe @mkhandekar decided to stick with the pop-up. This is ultimately a UX call. It can of course be reconsidered but just wanted to flag

OK great yes I just wanted to make sure it was raised for consideration :) That's exactly what I wanted to know, thanks!

**Comment by changecourse** [comment]
I don't think this is totally settled, fwiw. 

I'd like to propose an ideal state flow, then discuss technical implementation, and we can decide as a group whether or not the LOE is worth it for how we wish to approach the google auth.
