### ISSUE TITLE
Review draft and iterate on Rally privacy notice

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#120]
### Context
We need to create content and design for Rally's awareness and onboarding stages. 
Part of **Review and iterate on awareness and onboarding stages #119.** See this ticket for full context.

### Relevant resources
* Meghana to add draft flow.
* See #119 for all resources.

### Requirements
- Review draft and iterate on Rally privacy notice.

### Activities 
- [ ] Move draft content to refined content.
- [ ] Plan for discussion that solicits critique / reactions / responses about open questions and implementation details.
- [ ] Iterate based on feedback.

### Acceptance criteria
Document should should clarify what privacy on Rally means for users, and allow the design team to integrate into the UX.

### Deliverable
TBD: Google doc

### Estimated size
3 days

**Comment by Sydettemozilla** [comment]
Version 2 of Privacy notice reviewed and edited \. submitted for next review
