### ISSUE TITLE
Clean up the rally-web-platform repository

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-web-platform#14]
- [ ] remove WebScience
- [ ] clean up `package.json`
- [ ] clean up `tests` directory
- [ ] remove `schemas`
- [ ] update readme

**Comment by rhelmer** [comment]
@hamilton one thing you might want to consider is to split the svelte app from the rally-core-addon repository, so it keeps the history, and rewriting the history on this repository:

https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

If you don't care about the history that's fine, just a thought :)

**Comment by hamilton** [comment]
Good suggestion, but after thinking about it, I think we're good to just ditch the history.
