### ISSUE TITLE
Review Carla's work on sign in / create account flow

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#152]
- [ ] review content
- [x] review general user flow
- [x] identify (together) what can be stretched or component-ized further into the logged in experience

cc: @carla-moz

What's the best way to review it? Live walkthrough or some other method?

**Comment by jepstein** [comment]
this was reviewed at the 11/1/2021 cross-functional.
notes -- https://docs.google.com/document/d/1vTWcEK-uLvaX4yifa-u17Oz3WI1S7uFSTnYCMDywspg/edit#
