### ISSUE TITLE
Review Storybook work

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#153]
- [x] walkthrough Storybook progress 
- [x] provide initial feedback 
- [ ] share other examples of Storybook that have worked well cross functionally in the past

cc: @Carla-Moz  we can use our existing meeting next Tuesday (we can move it to whenever) for this 😄

**Comment by Carla-Moz** [comment]
@mkhandekar, yes! Let's do that. ;) Next Tuesday is still a good day.
