### ISSUE TITLE
Pick a URL for the Rally Web Platform

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#160]
We need to pick a new url to use when a user enters the Rally Web Platform (RWP) experience.
Engineering recommends that it be a separate domain from rally.mozilla.org, as the RWP is an authenticated experience and the Rally website is a static, unauthenticated experience.

Engineering recommends a new subdomain (i.e. xxxxx.mozilla.org).
So we should decide what that subdomain is.

This needs to be decided ahead of launch.

**Comment by jepstein** [comment]
myrally.mozilla.org?

**Comment by mkhandekar** [comment]
Out of curiosity, can it be rally.mozilla.org/account ?

**Comment by jepstein** [comment]
decision: members.rally.mozilla.org
