### ISSUE TITLE
Restore password strength parameters

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#170]
When I said remove caps in the all the screens in the last [cross functional meeting](https://docs.google.com/document/d/1vTWcEK-uLvaX4yifa-u17Oz3WI1S7uFSTnYCMDywspg/edit?disco=AAAARcr5v58), I did not mean to remove it from the password requirements themselves. 

![Screen Shot 2021-11-17 at 4 02 01 PM](https://user-images.githubusercontent.com/1598889/142289539-24ba34f4-2a14-44c0-9472-0605f83e6a28.png)

I meant to use sentence case instead of title case in the content of the UI (which I saw @Carla-Moz you did implement, I think!)

This ticket would like you to restore the password settings like they were before -- requiring capitalization to make it strong. 

Thanks!

**Comment by Carla-Moz** [comment]
No prob! I restored the uppercase password requirement.

**Comment by mkhandekar** [comment]
Woohoo!
