### ISSUE TITLE
Plan RWP Launch

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#211]
[Planning for launch](https://docs.google.com/document/d/1SFnJyz_wXH5lvA9UKG09marcRoDKfwnK7H0EC9BGvQI/edit#)

- [x] Sizing
- [x] Interactions/flows: refining w/ @mkhandekar

**Comment by marniepw** [comment]
Schedule: https://docs.google.com/spreadsheets/d/1ZN4zrW6jCF9ZHTkNgRffh4BpI0p3ZnzlbuRGmvSF9yY/edit#gid=0

**Comment by jepstein** [comment]
https://docs.google.com/spreadsheets/d/1ZN4zrW6jCF9ZHTkNgRffh4BpI0p3ZnzlbuRGmvSF9yY/edit#gid=0
