### ISSUE TITLE
Write high-level proposal for architectural change

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-web-platform#28]

**Comment by rhelmer** [comment]
Proposal is in a [Google doc](https://docs.google.com/document/d/1mm3W3Llqyr-4qzAm1RMv5bcZXEnSL7WE3jpB8rYlU_Q/edit#heading=h.jfklfq99vju4), I'd like to land the (mermaidjs) diagrams in this repo too along with anything we think is relevant.
