### ISSUE TITLE
Don't join this study card

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally-web-platform#390]
[Figma link to Don't join this study card](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2785%3A55105)

**Card**
Padding: 32px
Rounded edges: 4px

Use Secondary and primary product buttons

![Screen Shot 2022-05-06 at 5 43 12 PM](https://user-images.githubusercontent.com/59886626/167220230-ade5fdbb-ce23-4f66-89b4-a4f32f67ce36.png)

The card follows the same proportions and styles as "Leave study" and "Delete your Rally account":

[Figma link to card component ](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2530%3A43176)

![Screen Shot 2022-05-06 at 5 48 12 PM](https://user-images.githubusercontent.com/59886626/167220686-3ba3320c-df27-4f6a-8b6b-331a5135fa31.png)

**Comment by thomik-corp** [comment]
This has been fixed now.
