### ISSUE TITLE
[Bug] Clicking Manage Profile on Account Settings screen doesn't do anything

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#418]
**Describe the bug**

**To Reproduce**
1. Go to Account settings
2. Hit Manage Profile on the left had side

Nothing happens. You remain on the screen you were on.

**Expected behavior**
goes to /profile

**Screenshots**
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/444356/168614563-eb93b144-8a44-4f35-b149-4dcafd873484.png">

**Browser / OS:**
Chrome
 
**Additional context**

**Comment by Carla-Moz** [comment]
This will be fixed in my PR.

**Comment by jepstein** [comment]
I think this is actually related to https://github.com/mozilla-rally/rally-web-platform/issues/453.
