### ISSUE TITLE
[Bug] Disable Edit Email and Edit Password when signed with Google

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#429]
**Describe the bug**

**To Reproduce**
1. Sign in with a Google account
2. go to account settings

Edit Email and Edit Password are accessible on the left-hand side even though the user is signed in with Google.

**Expected behavior**
Edit Email and Edit Password do not appear as options

**Screenshots**
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/444356/168838831-39ecadb0-3b5e-4cd0-9436-4ac35f673f68.png">

**Comment by rhelmer** [comment]
One thing that wasn't clear to me from the Firebase docs until I tried it, is that it is possible to create an account with Google but then set a password and log in using that email address.

We don't need to allow it, but it appears to be the default behavior.

**Comment by jepstein** [comment]
I'm thinking this is about consistency for now. We chose to hide from the main account settings screen, so we should hide them from the sidebar, too.

That said, we should revisit this if when we iterate on account options.
