### ISSUE TITLE
[Bug] study ellipsis menu is not functional after first login before page refresh 

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-web-platform#444]
**Describe the bug**

**To Reproduce**
1. Go to https://members.rally.allizom.org
2. create new account, enroll, skip survey
3. join study but do not install extension
4. return to site tab, attempt to interact with Study "..." menu 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/61412/169109659-9d2bbcf8-5dd6-43a1-a0b2-71bd57576941.png">

Menu is not functional until after page reload

**Expected behavior**

Menu works on first try after login without requiring reload

**Screenshots**
If applicable

**Browser / OS:**
 
**Additional context**

**Comment by rhelmer** [comment]
This only seems to happen when the extension is not present, if the extension is present then the menu functions correctly.

**Comment by thomik-corp** [comment]
I cannot repro this. I don't have extension installed and when I enroll and come back to the page its just fine.

**Comment by jepstein** [comment]
I am able to reproduce this following the steps Rob laid out. Also signing that user out and back in, I get the same unexpected behavior.

**Comment by rhelmer** [comment]
Appears to be fixed by PR #446
