### ISSUE TITLE
[Bug] Trying to sign in with unverified email account doesn't display an error

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#458]
**Describe the bug**

**To Reproduce**
1. Create new email account
2. do not verify the email address
3. try to sign in

The Sign In button seems disabled and the experience feels like you are stuck.

**Expected behavior**
Expect an error (from Figma)
![Sign In](https://user-images.githubusercontent.com/444356/169571730-a7874951-c52f-481e-95c5-1be2fc39f7f0.png)

**Screenshots**

https://user-images.githubusercontent.com/444356/169571369-261344dc-4a9b-45b1-a24b-bd7a0367fff9.mov

**Browser / OS:**
 
**Additional context**

**Comment by rhelmer** [comment]
I think I might have regressed this by explicitly signing out the user if they log in and verification has failed:

https://github.com/mozilla-rally/rally-web-platform/blob/3ee47b046e0c3934e2f457eb0ee27feea9d6e328/src/lib/stores/api.js#L327

We should add a test for this, I know we test that users cannot log in, but we should test that the error message appears as well.

**Comment by rhelmer** [comment]
Oh, I see why this is happening, it's because Firebase throws this exception (rather than sending multiple verification emails every time the user clicks "Sign in"):
```
vendor-1dc907b8.js:337 Uncaught (in promise) FirebaseError: Firebase: Error (auth/too-many-requests).
    at bo (vendor-1dc907b8.js:337:587)
    at Fe (vendor-1dc907b8.js:337:30)
    at zu (vendor-1dc907b8.js:472:1198)
    at async pb (vendor-1dc907b8.js:997:482)
    at async Object.loginWithEmailAndPassword (app-store-d5f18b33.js:1:4408)
```

We need to catch that exception here: https://github.com/mozilla-rally/rally-web-platform/blob/3ee47b046e0c3934e2f457eb0ee27feea9d6e328/src/lib/stores/api.js#L326

**Comment by thomik-corp** [comment]
I don't see this behavior. Here is my experience (see video):

https://user-images.githubusercontent.com/85543848/170808462-45ebec3b-5c2f-4024-b576-7f491819f2a2.mov

**Comment by jepstein** [comment]
> Oh, I see why this is happening, it's because Firebase throws this exception (rather than sending multiple verification emails every time the user clicks "Sign in"):
> 
> ```
> vendor-1dc907b8.js:337 Uncaught (in promise) FirebaseError: Firebase: Error (auth/too-many-requests).
>     at bo (vendor-1dc907b8.js:337:587)
>     at Fe (vendor-1dc907b8.js:337:30)
>     at zu (vendor-1dc907b8.js:472:1198)
>     at async pb (vendor-1dc907b8.js:997:482)
>     at async Object.loginWithEmailAndPassword (app-store-d5f18b33.js:1:4408)
> ```
> 
> We need to catch that exception here:
> 
> https://github.com/mozilla-rally/rally-web-platform/blob/3ee47b046e0c3934e2f457eb0ee27feea9d6e328/src/lib/stores/api.js#L326

Rob's right. This seems to be a symptom of the [too many requests issue](https://github.com/mozilla-rally/rally-web-platform/issues/468).
Fixing #468 should fix this.

**Comment by jepstein** [comment]
won't fix

**Comment by aaga** [comment]
Fixing with a temporary measure; will address the broader issue of too-many-requests separately in #468
