### ISSUE TITLE
[Bug] use members.rally.mozilla.org as auth domain for Google Authentication

### ISSUE THREAD

**Issue by rhelmer** [mozilla-rally/rally-web-platform#464]
**Describe the bug**

**To Reproduce**
1. Go to https://members.rally.mozilla.org
2. note domain name

**Expected behavior**

Domain name displayed should be `members.rally.mozilla.org` not `[...].firebaseapp.com`

**Screenshots**
![image](https://user-images.githubusercontent.com/61412/169618654-011b9c7c-af40-43f8-a2d0-5295ec9d570a.png)

Note, we attempted to change this in https://github.com/mozilla-rally/rally-web-platform/pull/416 but something still needs to be configured in the backend:

![image](https://user-images.githubusercontent.com/61412/169618631-77f7b0e3-e4e9-4289-b398-a0462d67ac3e.png)

**Browser / OS:**
 
**Additional context**

**Comment by rhelmer** [comment]
OK per the top answer in https://stackoverflow.com/questions/40856179/custom-authdomain-in-firebase, this is the "Authorized redirect URIs" that need to be set in GCP directly, this can't be controlled from the Firebase console.

I'm having trouble finding a more official source like the GCP/Firebase docs, let's verify that this is correct.

**Comment by cmharlow** [comment]
I'm not getting the redirect error you're showing here - is that if you try to go to the firebaseapp.com url instead of members.rally.mozilla.org? Regardless, making a SRE ticket for this so I can go figure out what was manually done in stage that needs to be replicated in prod.

**Comment by rhelmer** [comment]
@cmharlow thanks! I backed this change out so it's not live, but what I did was change the authDomain in the firebase SDK client config, so I didn't make any changes to the backend.

That changes the redirect domain that is displayed here:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/61412/169874939-580210bd-4051-49a0-b8ec-ecb2897197f6.png">

It was displaying the redirect domain correctly, but we were getting that error trying to complete sign-in, so I backed that change out.

**Comment by cmharlow** [comment]
okay, yeah, I was about to say that needs to change in the client code. When you have a moment, please retry that change for stage and see if this all works as intended now.

**Comment by cmharlow** [comment]
I've updated the OAuth 2.0 Client IDs in GCP for rally-web-nonprod (for now) project to include the new authorized domains in JS origins and redirect URIs. I'll do the same in prod if this works.

**Comment by rhelmer** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/61412/169921540-ef74401e-594f-4684-a7f6-8aec883f3c45.png">
<img width="522" alt="image" src="https://user-images.githubusercontent.com/61412/169921558-5b37f7c5-0a76-45c5-80dd-1f6a27846276.png">
