### ISSUE TITLE
[Bug] In the not participating state, the meatball menu doesn't do anything

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-web-platform#484]
**Describe the bug**

**To Reproduce**
1. Sign up for a Rally account and clicked on Join Study. 
2. I can't actually join the study b/c it's not live on the Chrome store.
3. Go to https://members.rally.mozilla.org/studies
4. Note that I'm in the in between state (see screenshot)
5. I assumed clicking on the meatball menu would help, but it doesn't do anything. I suspect Carla's most recent PR might handle this case.

**Expected behavior**
I expect the meatball menu to either give me the option to add the study extension from the Chrome store, or not be visible.

**Screenshots**
<img width="726" alt="Screen Shot 2022-05-24 at 5 01 30 PM" src="https://user-images.githubusercontent.com/33703387/170151472-08e1e27a-2102-4adc-b78c-194e5f0e6a3e.png">

**Browser / OS:**
 Version 102.0.5005.61 (Official Build) (x86_64) / IOS

**Additional context**

**Comment by jepstein** [comment]
I am unable to reproduce this now.
This is a duplicate of https://github.com/mozilla-rally/rally-web-platform/issues/444 that we fixed.

Was this a google signin or email/password?

**Comment by marniepw** [comment]
Email/password. 

And yes, a dupe. Closing.
