### ISSUE TITLE
[Bug] Footer has two Data & Privacy links

### ISSUE THREAD

**Issue by pdehaan** [mozilla-rally/rally-web-platform#493]
**Describe the bug**
The https://members.rally.mozilla.org page has two "Data & Privacy" links in the footer.

**To Reproduce**
1. Go to https://members.rally.mozilla.org
2. Look at the footer
    - The first "Data &amp; Privacy" link goes to https://members.rally.mozilla.org/terms
    - The _second_ "Data &amp; Privacy" link goes to https://rally.mozilla.org/how-rally-works/data-and-privacy/

**Expected behavior**
Only one "Data &amp; Privacy" link. Not sure if one of the labels is wrong, but it is a bit confusing.

**Screenshots**

![Screen Shot 2022-05-25 at 7 56 10 PM](https://user-images.githubusercontent.com/557895/170406539-513a4137-58ba-4be3-b2d2-15c17cb6e414.png)

**Browser / OS:**
macOS 12.2 Chrome Stable 

**Additional context**

**Comment by jepstein** [comment]
Casey is reworking the footer
