### ISSUE TITLE
[Bug] Two "Support" links in members.* footer

### ISSUE THREAD

**Issue by pdehaan** [mozilla-rally/rally-web-platform#500]
**Describe the bug**

**To Reproduce**
1. Go to https://members.rally.mozilla.org/studies
2. Scroll down to footer
3. Note that we have two "Support" links that go to the same place; https://support.mozilla.org/en-US/kb/about-mozilla-rally

**Expected behavior**

**Screenshots**
![Screen Shot 2022-05-25 at 11 19 36 PM](https://user-images.githubusercontent.com/557895/170429374-b6ea3ba5-4011-4ff6-bfbf-b5ed110f2025.png)

**Browser / OS:**
 
**Additional context**

**Comment by jepstein** [comment]
Casey is reworking the footer
