### ISSUE TITLE
[Bug] Sign Out button in dropdown only works if you click on the text

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally-web-platform#502]
**Describe the bug**

**To Reproduce**
1. Go to members.rally.mozilla.org
2. Sign in
3. Make sure window is wide enough so you don't have the hamburger menu
4. Click the person icon in the top right
5. Click the Sign Out box outside the area with text in it e.g. to the far right of the box

**Expected behavior**
Doing this should log you out but instead is a no-op.

**Screenshots**
<img width="325" alt="Screen Shot 2022-05-26 at 2 12 28 PM" src="https://user-images.githubusercontent.com/7362472/170550177-6619de90-85cb-491c-84d5-c43155a50fcb.png">

**Comment by rhelmer** [comment]
Oh, good catch... I was wondering what was going on here since it seemed to take multiple clicks, but I couldn't reproduce it.
