### ISSUE TITLE
Footer: update

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally-web-platform#503]
# Footer

[Figma link](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=3317%3A57502)

<img width="787" alt="Screen Shot 2022-05-31 at 2 15 02 PM" src="https://user-images.githubusercontent.com/59886626/171256684-661e4607-03f5-4aaa-9ce0-25ef20222ded.png">

Newsletter link: https://rally.mozilla.org/newsletter/index.html

**Comment by tangcasey** [comment]
[Figma link](https://www.figma.com/file/L4z8XxuFrbGgN83oe3gjh5/Mozilla-Rally-%E2%80%93-Website-(rally.mozilla.org)?node-id=741%3A170)

**Comment by Carla-Moz** [comment]
@tangcasey  and the contact us link?
