### ISSUE TITLE
Draft implications for data collection, retention and deletion

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#51]
### Context
We need to understand and document what policy requirements we must meet in regards to data collection, retention and deletion. And, what we are planning on implementing for the new experience.

### Relevant resources
* [Rally Web Platform Architecture](https://docs.google.com/document/d/1mm3W3Llqyr-4qzAm1RMv5bcZXEnSL7WE3jpB8rYlU_Q/edit)
* [Mozilla Rally Firebase Operations Plan](https://docs.google.com/document/d/1hMPtVuxApR1u1O-pv6vb7l0K9Ujae9lcl4KUVFQF1Uc/edit#)

### Requirements
The document should explain requirements and implementation details for...
1. leaving a study
2. leaving Rally
3. logging out
4. ... identify if this list is missing scenarios!

### Activities 
- [x] @hamilton to write draft 
- [x] Review with team on Friday
- [x] With team, identify what constitutes "done" for this. Refine based on team needs. 

### Acceptance criteria
Details in the draft meets team needs to make design and implementation decisions

**Comment by hamilton** [comment]
I've produced a draft of the doc [here](https://docs.google.com/document/d/1HJHnDwS9ihPx8HexcWjKOzg0iIoY-sAfYAv1VILVFeg/edit#).

We will be producing some diagrams to outline additional edge cases that we have not figured out yet.

**Comment by mkhandekar** [comment]
I think we can close this. We've documented the edge cases, and moved on to the diagramming stage.
