### ISSUE TITLE
Studies page doesn't detect installed extension 

### ISSUE THREAD

**Issue by lfrancis** [mozilla-rally/rally-web-platform#519]
The Studies page doesn't detect installed extension.

**To Reproduce**
1. With there extension installed, go to https://members.rally.mozilla.org/studies
2. Examine the Study notification message 

**Expected behavior**
Having previously installed the extension, I expected the page to recognize the study extension as present.

**Screenshots**
![image](https://user-images.githubusercontent.com/6942589/171703588-92e344b4-75db-4312-8004-afd9775221ef.png)

**Browser / OS:**
 MacOS Catalina 10.15.7 / Chrome 102

**Comment by lfrancis** [comment]
Upon forced-reload the Study page recognized the extension.

**Comment by rhelmer** [comment]
Thanks for the report @lfrancis! This is a known issue, the extension can't load its content script until the page is reloaded, so the website and extension cannot message each other.

The post-install function of the extension is supposed to find and reload any open tabs, but I think this might not be working as intended on Chrome - it seems to open a new tab, vs. Firefox where it finds, focuses, and reloads the tab as intended.

Note that there is a similar issue where the website cannot detect uninstall of an extension, I think we need https://github.com/mozilla-rally/rally/issues/109 to do this reliably.
