### ISSUE TITLE
Plus-addressing breaks account management

### ISSUE THREAD

**Issue by lfrancis** [mozilla-rally/rally-web-platform#525]
I changed my email address to add plus addressing, which was accepted by the back-end and reflected in my email notification, however when I sign out and try to log back in using my new plus address I get an _Account does not exist_ error for that new email address. Removing the plus content from the email input field then allows for a successful login.

**To Reproduce**
1. Go to https://members.rally.mozilla.org/account-settings
2. Click on Edit for the email address. 
3. Add plus content to the email address, i.e. foo+x@foo.com where the plus content is "+x" 
4. Enter the current password and submit. 
5. Open your email client and look for the confirmation email, check that the new email address is present and click on the verification link.
6. Sign out, then sign back in using the new plus address.

**Expected behavior**
I expected a successful login.

**Screenshots**
![image](https://user-images.githubusercontent.com/6942589/171726416-edfc9565-4c6f-4a13-8a3f-035d10d0ee92.png)

![image](https://user-images.githubusercontent.com/6942589/171727137-42924901-77a5-418c-815c-acd4d0c0b3d3.png)

**Browser / OS:**
 Catalina/Chrome 102

**Additional context**

**Comment by lfrancis** [comment]
It appears that while the new plus address is reflected in the email body, the actual email address used for sending the notification message is to the non-plus address, IOW lewis.francis@threespot.com.

**Comment by jepstein** [comment]
I have not been able to reproduce this. I even wondered if there was something about having both the . and + in the address. Looking up to see what state your accounts might be in.

(thank you for all the testing and bug filing)

**Comment by jepstein** [comment]
Could you try again? We've been using + in our testing and not seeing issues.
What may be confusing things is the UI around this. Changing the email triggers two emails -- (a) the screenshot you sent and (b) an email verification email.

If you hit the link in (a), you are reseting your email to the original one.
In (b), there's a link to verify your new email address.

Currently, we only see your lewis.francis@threespot.com address in our database.
