### ISSUE TITLE
Account Setting - Side Nav / hover state

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally-web-platform#532]
On the account settings page: if the user clicks "Edit" on the page (not sid nav), the user is presented with the appropriate page but it's not reflected in the sid nav

Account Setting > Edit password > Change your password modal 
- does not update in sid nav
<img width="968" alt="Screen Shot 2022-06-03 at 10 59 21 AM" src="https://user-images.githubusercontent.com/59886626/171880546-1e319364-13d8-44c2-98b0-2bb706587b6d.png">

Happens to all pages 
<img width="970" alt="Screen Shot 2022-06-03 at 10 59 14 AM" src="https://user-images.githubusercontent.com/59886626/171883362-feaaf238-6660-45c3-8ef5-da2877c8b513.png">

**Comment by thomik-corp** [comment]
This is resolved now. https://github.com/mozilla-rally/rally-web-platform/pull/508
