### ISSUE TITLE
Account Setting - Link button style / add hover and press style 

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally-web-platform#534]
Currently. there's no hover or press style for link button style:

Figma reference: [Link states](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=3394%3A58456)
or refer to [rally.mozilla.org](rally.mozilla.org
)

Two types of link styles:

Link as it appears in content
Persistent navigation: Top nav and footer

<img width="811" alt="Screen Shot 2022-06-03 at 11 34 44 AM" src="https://user-images.githubusercontent.com/59886626/171891264-34076506-294f-4aa2-8c9b-706c1792fe9f.png">

Please copy the link style on rally.mozilla.org site 

<img width="456" alt="Screen Shot 2022-06-03 at 11 37 03 AM" src="https://user-images.githubusercontent.com/59886626/171892383-7a568f67-772c-4b10-bc4c-1ea6b7f35b5f.png">

**Comment by Carla-Moz** [comment]
@tangcasey, so underline on hover and no text decoration on default? That's what I see going on in rally.mozilla.com.

**Comment by Carla-Moz** [comment]
Ah, I see. I was looking at the top nav links. It's confusing since the hover states are different. :/

**Comment by tangcasey** [comment]
@Carla-Moz

There are two types of link styles: 

# Content Link style 1
^ I'll just call this 

Default: Underline
<img width="494" alt="Screen Shot 2022-06-03 at 1 54 43 PM" src="https://user-images.githubusercontent.com/59886626/171919745-66f0f5ac-b5ac-483f-a918-67a6ecff0f5e.png">

Hover: No underline
<img width="484" alt="Screen Shot 2022-06-03 at 1 55 07 PM" src="https://user-images.githubusercontent.com/59886626/171919802-6917d859-cde2-4d13-95df-1c3fb10ba0a7.png">

Press: grey highlight
<img width="757" alt="Screen Shot 2022-06-03 at 1 56 24 PM" src="https://user-images.githubusercontent.com/59886626/171920037-bdf2d289-4d90-4e8a-b5ae-22f4ae64ee05.png">


You can check figma too
<img width="608" alt="Screen Shot 2022-06-03 at 1 58 54 PM" src="https://user-images.githubusercontent.com/59886626/171920392-c279f9d7-f585-4558-987f-349e68849106.png">

We currently have this type of link style in account creation, sign-in, and account settings - they should all the same interaction 


## Account creation

## Sign-In

## Account settings


# Persistent navigation link style
^ The other type of link style appears in the top navigation and footer
Its important we keep this consistent since these really tie the two pages together

Default: No text decorations
Hover: Underline
Press: No text decorations

**Comment by tangcasey** [comment]
> Ah, I see. I was looking at the top nav links. It's confusing since the hover states are different. :/

Yeah but its what we got until we rebrand the whole thing - because we would have to change the Rally website to match the Rally web platform. Currently, the idea was to match the RWP to the Rally website.

**Comment by Carla-Moz** [comment]
Ok, thanks for clarifying.
