### ISSUE TITLE
Security review: start convo w/SecOps

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#54]
As a Rally user, I want my data to be securely stored and accessed.

**Comment by jepstein** [comment]
RRA request filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1724746

**Comment by jepstein** [comment]
Meeting scheduled for 8/16

**Comment by hamilton** [comment]
This is a duplicate of #30; closing the older issue in favor of this one.

**Comment by jepstein** [comment]
Two follow-ups before the official readout -

https://github.com/mozilla-rally/rally-web-platform/issues/68
https://github.com/mozilla-rally/rally-web-platform/issues/69
