### ISSUE TITLE
Migrate svelte site to monorepo - OR - use migrated functions

### ISSUE THREAD

**Issue by thomik-corp** [mozilla-rally/rally-web-platform#542]
We need to assess what is best approach for interim state until React migration completes:
- Should we move svelte website to monorepo since functions are already being migrated there
- OR
- Should we deprecate and remove functions from this repo and take dependency on monorepo folder.

If we go with first approach we need to ensure we can publish to firebase hosting.

**Comment by marniepw** [comment]
Decision: move forward with option #2.
