### ISSUE TITLE
[story] Web Platform needs to support different extension store links for different browsers

### ISSUE THREAD

**Issue by aaga** [mozilla-rally/rally-web-platform#587]
## Story

At a minimum, when a user visits the RWP from Chrome vs Firefox, the study extension link should be different (i.e. take them to the respective store).

## Definition of Done

Click "Add Study Extension" takes you to the correct store for your browser.

## Tasks
- Detect browser with User-Agent
- Change Firebase schema to support downloadLink for multiple browsers
- Use the appropriate link in the front-end

**Comment by marniepw** [comment]
Can't test front end fix until back end lands. 

Plan: 

1. land back end fix first, front end tests should pass. 
2. Next, land front end fix. Press "load firestore ..."

Also with this change:

- unsupported browsers: will show "no supported studies"
- updated instructions for installing a study
