### ISSUE TITLE
Develop test plan for MVP release

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#61]
We need a test plan on what and how we're going to test the MVP release.

DOD:
Identify flows and test cases for automation (Selenium) and manual

**Comment by rhelmer** [comment]
I have a PR ready for review, which uses Selenium and walks through as much of the existing UX flow that works:
https://github.com/mozilla-rally/rally-web-platform/pull/79

That's just a starting point though, I'd like to come up with a bit more of a plan before we close this.

**Comment by marniepw** [comment]
Identify specific flows that we want to have automated testing for vs. manual testing.
