### ISSUE TITLE
Produce draft of figma diagrams for user flow / user state

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla-rally/rally-web-platform#62]
- Start with translating Rob’s diagram
- Golden path user flows
- Edge cases

![image](https://user-images.githubusercontent.com/88336547/129081440-28edab23-55fa-4451-9eaa-eb7596a2d7ac.png)

relevant link: [Mapping User Consent...](https://docs.google.com/document/d/1HJHnDwS9ihPx8HexcWjKOzg0iIoY-sAfYAv1VILVFeg/edit#heading=h.xehrqz8c8ib6)

**Comment by hamilton** [comment]
Closing this issue as described; we had a productive session on Friday utilizing the diagrams we had laid out.
