### ISSUE TITLE
Proposal: Outline all potential user states in the new Rally Web Platform

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-web-platform#66]
Make an outline of each potential state and edge case and how users might get into them and rough ideas for how they can get out/back. After an outline has been put together, work with Meghana to map out in more detail the ideal routes a user can take.

We could do this in the current ["user consent & data platform consequences"](https://docs.google.com/document/d/1HJHnDwS9ihPx8HexcWjKOzg0iIoY-sAfYAv1VILVFeg/edit?usp=sharing) doc.

**Comment by jepstein** [comment]
State breakdown - https://docs.google.com/document/d/1HJHnDwS9ihPx8HexcWjKOzg0iIoY-sAfYAv1VILVFeg/edit#heading=h.akb5wwiecocp
