### ISSUE TITLE
Rally coding standard / style guide 

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla-rally/rally-web-platform#67]
Create a document that the engineering team can collaborate on to produce a complete style guide for the rally web platform.

**Comment by mkhandekar** [comment]
@Carla-Moz (not timely or urgent):

I suggest moving this to Sprint 23. @jepstein  and I are meeting early next week to discuss our shared expectations for these topics and how we want to handle them throughout product development. We will share outcomes that will hopefully help you and @changecourse (and future teammates) develop the Rally coding standard / style guide (and I'm adding design standards) to this as well.

- Grids
- Responsiveness
- Accessibility 
- Behavior on mobile
- And how to make decisions related to these topics

When you're back, and if you agree, feel free to push this to Sprint 23.

**Comment by Carla-Moz** [comment]
Sounds like an awesome idea. I'll work on publishing the document on Google drive by EOD so we can all start adding to it.
