### ISSUE TITLE
Figure out how tokens get passed from website to extension

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#68]

**Comment by rhelmer** [comment]
The place with the most implementation-level detail right now is https://docs.google.com/document/d/1AQpBaj8ll-MCYFyon10zsK7DgZ_n9tpTZZbaF-7ZInw

**Comment by rhelmer** [comment]
Message-passing of a JWT for use by the extension is now implemented in both rally-web-platform and also rally-sdk, and is documented in https://docs.google.com/document/d/1w51IoO92PgZm6LvoJUmnlKeMeWmntFTB7_bpKtJiuLk/
