### ISSUE TITLE
Figure out how to update study metadata firestore

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#69]

**Comment by rhelmer** [comment]
I've described this in https://docs.google.com/document/d/1AQpBaj8ll-MCYFyon10zsK7DgZ_n9tpTZZbaF-7ZInw/edit#heading=h.1oqyrz19aytf and discussing it with secops/sre and google/firebase folks this week.

I've also implemented a basic version of it to get integration tests working in https://github.com/mozilla-rally/rally-web-platform/pull/79
