### ISSUE TITLE
Task of #117: Add client-side form validation  

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla-rally/rally-web-platform#99]
Validate the forms on the signup page to give users feedback

**Comment by marniepw** [comment]
Task of: https://github.com/mozilla-rally/rally-web-platform/issues/117

**Comment by Carla-Moz** [comment]
Placeholder validation until complete design:

1.	Added required attribute to email and password forms
2.	Added font-awesome for password eye icons
3.	Allowed user to see or hide their password
4.	Added new rules:user must enter a minimum of 8 characters for password and use 1 number, 1 uppercase, 1 special character 
5.	Added basic Firebase error warnings :
  a.	Email already exists
  b.	Password is invalid. Please try again.
